#services:
#  db-arm:

#    image: mysql:latest
#    container_name: db-arm
#    networks:
#services:
#  db-arm:
#    image: mysql:latest
#    container_name: db-arm
#    networks:
#      - arm-mreza-zadaca
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
#      MYSQL_DATABASE: wt24
  # docker build -t nodejs-app-wt:v1.0 .
  #docker run -dp 3000:3000 --network arm-mreza-zadaca --name nodejs-app-wt nodejs-app-wt:v1.0
#  nodejs-app:
#    build: .
#    image: fkaljanac1/arm-zadaca:v1.0
#    container_name: nodejs-app-wt
#    ports:
#      - "3000:3000" # Format: <HOST_PORT>:<CONTAINER_PORT>
#    networks:
#      - arm-mreza-zadaca
#    depends_on:
#      - db-arm
#    deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 10

#networks:
#  arm-mreza-zadaca:
#    name: arm-mreza-zadaca
#    driver: bridge
#    external: true

#      - arm-mreza-zadaca
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
#      MYSQL_DATABASE: wt24

  # docker build -t nodejs-app-wt:v1.0 .
  #docker run -dp 3000:3000 --network arm-mreza-zadaca --name nodejs-app-wt nodejs-app-wt:v1.0
#  nodejs-app:
#    build: .
#    image: fkaljanac1/arm-zadaca:v1.0
#    container_name: nodejs-app-wt
#    ports:
#      - "3000:3000" # Format: <HOST_PORT>:<CONTAINER_PORT>
#    networks:
#      - arm-mreza-zadaca
#    depends_on:
#      - db-arm
 #   deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 10
#networks:
#  arm-mreza-zadaca:
#    name: arm-mreza-zadaca
#    driver: bridge
#    external: true
